### ISSUE TITLE
February 2017

### ISSUE THREAD

**Issue by vykster** [compilerla/data-donuts#1]
- [x] Confirm Speaker
  - [x] Headshot uploaded to website
  - [ ] Bio posted on website
- [x] Confirm Location
  - [x] Location added to website
  - [ ] AV setup confirmed
- [x] Confirm Catering
  - [x] Coffee
  - [x] Donuts
- [ ] Comms
  - [x] One sheet pitch deck for GIS Day (Juan & Melissa)
  - [ ] Tweets scheduled using hashtag
  - [ ] Posted to Facebook
  - [ ] RSVP email sent to email list
  - [x] City TV confirmed
  - [ ] Live tweeter during event assigned has speaker handles, event hashtag
  - [ ] Event photographer
- [ ] Swag and materials (sign, stickers, etc)

Post Event
- [ ] Video of talk uploaded to internet and linked to site
- [ ] Thank you for attending email, link to video and rsvp for next event
- [ ] Website updated for next event!
- [ ] 

flyers, nametags

**Comment by vykster** [comment]
- [ ] test

**Comment by patwater** [comment]
-[ ] test
-[x] test

**Comment by matikin9** [comment]
# 12/21/16 Notes

* Speaker - Juan Lopez
* Location - LACI, Bradbury Room, or Impact Hub [Juan & Melissa]
* Catering
  * Coffee - Starbucks or Wheelhouse [Juan & Melissa]
  * Donuts - 4 dozen needed [Nina]
* Comms
  * One-pager - have Jon confirm
  * Social Media/Emails - send out first week of January
  * Website - [Vyki]
  * Eventbrite - [Vyki]
* Swag
  * Stickers - ordered [Melissa]
  * Bags with logo - [Vyki]
* Day of Logistics
  * Laptop for sign-in
  * Google Form (?) to collect emails
  * Determine setup & breakdown time needed
  * Setup/breakdown roles

**Comment by matikin9** [comment]
![d d facebook 1](https://cloud.githubusercontent.com/assets/1873072/22310026/92858e0e-e302-11e6-93bd-bdfd88a4b180.png)
![d d twitter](https://cloud.githubusercontent.com/assets/1873072/22310027/929aa6c2-e302-11e6-9615-ebc21dcefbf9.png)
[D&D Flyer (4).pdf](https://github.com/compilerla/data-donuts/files/730989/D.D.Flyer.4.pdf)
