### ISSUE TITLE
Close August 2023 event

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/data-donuts#103]
Move the [August event](https://datadonuts.la/event/data-donuts-37.html) to [past events](https://datadonuts.la/).

**Comment by AnthonyRollins** [comment]
@thekaveman, Could you help me with moving this event to close?

**Comment by thekaveman** [comment]
@AnthonyRollins it is actually not that straightforward. 

The code that generates the the "Upcoming event" uses the date of the _last time the website was rebuilt_ i.e. the last time a change was made. This is the same problem we had to solve in Compiler's website with the job post expiry.

A quick fix is just to make any change at all to the website to force a rebuild. I can also look at making a workflow that will allow you to rebuild the site on-demand (without having to make a change). Ideally for the future we re-code this to be similar to how the job posts work.
