### ISSUE TITLE
Manually run the build and deploy workflow

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/data-donuts#105]
We need to rebuild the site by making small changes to the code base to move events from current to past; see #103 for contents. Instead of making minor changes to the site, we can update the workflows so that anyone can run them manually without having to edit the code.

**Comment by thekaveman** [comment]
Ok, this is now possible! Here's a quick GIF of the process:

![actions-deploy](https://github.com/compilerla/data-donuts/assets/1783439/fc4ba717-7143-4825-9499-009dabb00b0c)

1. Click on the `Actions` tab in the repo
2. Find and click the workflow on the left menu bar `Deploy Jekyll site to Pages`
3. Look for the `Run workflow` button on the right of the main panel, open this, ensure `main` is the branch, and click `Run workflow`
4. Refresh the page to see a new run scheduled, click on this run to go to a details page
5. Wait for the `build` and `deploy` jobs to complete

When everything is finished, both jobs will have a green check ✔️ and a link to the site will be presented:

<img width="542" alt="image" src="https://github.com/compilerla/data-donuts/assets/1783439/91fa99f6-10ab-4b70-b50c-56d603693083">

**Comment by thekaveman** [comment]
@AnthonyRollins let me know if this makes sense and if you can go through the steps. We may need to bump you even higher into `Admin` to be able to run the workflow, per #106.

**Comment by AnthonyRollins** [comment]
@thekaveman I just ran the action, and it is working, so I think I have all the permissions.
