### ISSUE TITLE
Update permissions for Anthony

### ISSUE THREAD

**Issue by AnthonyRollins** [compilerla/data-donuts#106]
Update permissions for @AnthonyRollins to the data-donuts repo.

**Comment by thekaveman** [comment]
@AnthonyRollins do you have the permissions you need here?

Are you able to run the deployment workflow manually? https://github.com/compilerla/data-donuts/issues/105#issuecomment-1734341383

**Comment by AnthonyRollins** [comment]
Everything looks good for me.
