### ISSUE TITLE
Potential Speaker: Ted Ross

### ISSUE THREAD

**Issue by melpete** [compilerla/data-donuts#15]
**Title & Employer:**
General Manager & CIO  
Information Technology Agency (ITA), City of Los Angeles

**Twitter:**
[@TedRossLA](https://twitter.com/TedRossLA)

**Headshot & Bio:**
![Ted Ross Twitter](https://pbs.twimg.com/profile_images/593166048641163264/LVbtIEHi_400x400.jpg)

> Ted Ross is CIO for the City of Los Angeles and General Manager for the Information Technology Agency (ITA).  His department delivers enterprise IT services to over 48,000 employees across 38 City departments and digital services to almost 4 million residents across 469 square miles.  Comprised of 455 dedicated employees with a $90 Million annual operating budget, his department supports more than 125 City applications, a 24/7 Data Center, City Data & Voice Communications, the 3-1-1 Call Center, Public Safety Microwave & Radio Communications, and the LA CityView Channel 35 TV Station.  Ted has over 21 years of private and public sector technology experience, earning various awards and IT credentials along the way.

**Comment by hunterowens** [comment]
Happy to facilitate an intro obviously, I'm sure Ted would be happy to
speak.
