### ISSUE TITLE
February 2, 2017 Recap

### ISSUE THREAD

**Issue by matikin9** [compilerla/data-donuts#21]
Attendee concerns: Parking.
Check-ins: Use the Eventbrite app to scan tickets.  Gather names and emails for non-RSVPd people.

All numbers are excluding the organizers & the speaker:
- 53 attendees checked in
  - 12 city staff
  - 25 county staff
  - 13 general public
  - 3 unknown
- 35 attendees RSVP'd
- 3 attendees were from the Waitlist
- 15 attendees did not RSVP
- 21 RSVPs were no-shows

**Comment by vykster** [comment]
+ Snafu with Eventbrite log-in, make sure everyone has access in advance.
+ Coffee showed up -- but should have called and confirmed day before

**Comment by matikin9** [comment]
ah haha, this is where I posted the numbers! :D

**Comment by vykster** [comment]
Live video from Galperin, should add to post.
https://www.facebook.com/rongalperin/videos/10211837158028388/?hc_ref=PAGES_TIMELINE

**Comment by vykster** [comment]
Vyki no longer has Facebook, need to check video before posting// see if we can get a non FB copy.
