### ISSUE TITLE
March 2017 Data and Donuts 

### ISSUE THREAD

**Issue by Jon-Neill** [compilerla/data-donuts#22]
Need to determine:

- [x] Date
 March 15th 2017
- [x] Location
 LACI
- [x] Speaker:
 Jeramy Gray
 Assistant Executive Officer – L.A. County Board of Supervisors, Executive Office
 Information Technology for Los Angeles County
- [x] Refreshments:  L.A. County will arrange.

ToDo:
- [x] [Create Eventbrite event](https://www.eventbrite.com/e/data-donuts-tickets-32492458819)
- [x] Add new event to website
- [ ] Email listserv (MailChimp) with invite
- [ ] Social Media blast event

**Comment by melpete** [comment]
Updated social media and flyer:
![march - d d facebook](https://cloud.githubusercontent.com/assets/23391197/23523550/40b255b6-ff3c-11e6-96bc-5e318729d72e.png)
![march - d d twitter](https://cloud.githubusercontent.com/assets/23391197/23523563/4ac30b2c-ff3c-11e6-868c-a954ef504d4b.png)
[March - D&D Flyer.pdf](https://github.com/compilerla/data-donuts/files/814893/March.-.D.D.Flyer.pdf)

**Comment by melpete** [comment]
Nametags:
![data donuts nametags](https://cloud.githubusercontent.com/assets/23391197/23523583/6305e2cc-ff3c-11e6-965b-7c515805a512.png)

**Comment by patwater** [comment]
Any chance we can have some healthy food alternatives to donuts this time?  :)

**Comment by vykster** [comment]
@patwater we'll think about it the future, but we don't have the bandwidth to plan for it yet!

Also you know, branding. ;)

**Comment by melpete** [comment]
updated flyer:
[March - updated D&D Flyer.pdf](https://github.com/compilerla/data-donuts/files/815256/March.-.updated.D.D.Flyer.pdf)

**Comment by matikin9** [comment]
Add LACI logo (AND HFLA LOGO?!) to website.

**Comment by Jon-Neill** [comment]
I think both logos are perfectly cromulent!
