### ISSUE TITLE
Talk descriptions

### ISSUE THREAD

**Issue by underthecurve** [compilerla/data-donuts#23]
Would be helpful if you could add talk descriptions in the email in addition to the speaker name/title, for those of us who might not know much about the speaker! Thanks.

**Comment by vykster** [comment]
@underthecurve yes! great idea. We're trying to improve a little bit each month, we'll add descriptions to the emails next month!

**Comment by vykster** [comment]
D+D team is including bios in emails, we're not always able to get a talk description in advance.
