### ISSUE TITLE
Breakout/Discussion Sections

### ISSUE THREAD

**Issue by hunterowens** [compilerla/data-donuts#27]
Hey All- 

Maybe with the 30 minutes post speaker, we do a breakout or discussion section about how we want to change `blank` practice or procedure in our departments. Would randomly assign groups based on nametags or something. 

-Hunter

**Comment by patwater** [comment]
That could work nicely if we have a speaker focused on a specific data issue like say homelessness (or water ;) ) and then the break outs could focus on how different municipalities and departments within said municipalities could help share data and integrate strategies to address said issue.  Good idea 👍
