### ISSUE TITLE
Catering!

### ISSUE THREAD

**Issue by vykster** [compilerla/data-donuts#3]
Orgs or companies to ask:

Potential Donuts
Birdies LA
Dunkin Donuts
BlueStar Donuts
California Donuts
Downtown Donuts
Donut Snob

Potential Coffee
Starbucks
Dunkin Donuts
Demitasse
Verve
Blue Bottle
Cognoscenti Coffee
Wheelhouse

**Comment by vykster** [comment]
Sent email to Wheelhouse today for a quote for Jan 12th.

**Comment by matikin9** [comment]
Asked my local shop, Munchkin Donuts - it'll be $35 for 4 dozen.

**Comment by melpete** [comment]
**Donut Ideas**
- Dunkin' Donuts	
- Pie Hole: Usually donate a few pies
- Downtown Donuts	
- Cafe Dulce	
- Donut Snob (delivery-only)	$37.50/12 standard, $42/24 mini
- Birdies LA
- California Donuts

**Comment by melpete** [comment]
**Coffee Ideas**

- Dunkin Donuts
- Pie Hole
- Starbucks
- Downtown Donuts
- Cafe Dulce
- Birdies LA
- Demitasse
- Verve
- Blue Bottle
- Wheelhouse
- Stumptown
- Cognoscenti
