### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by vykster** [compilerla/data-donuts#4]
![data-donuts-home](https://cloud.githubusercontent.com/assets/4284662/20190280/99332a6c-a735-11e6-9ab0-b815228042b7.png)

**Comment by vykster** [comment]
Vyki buy domain and set up a splash page.

**Comment by vykster** [comment]
Bought domain: datadonuts.la, waiting for dns to go through.

**Comment by vykster** [comment]
Mailchimp account setup.

Todo:
- [ ] set up email for datadonuts.la (forward to ??)
- [ ] config dns

**Comment by melpete** [comment]
![dnd logo](https://cloud.githubusercontent.com/assets/23391197/22047321/2662bd8c-dcdb-11e6-9bf8-3c72c53c7ad4.png)

**Comment by melpete** [comment]
![data and donuts blk](https://cloud.githubusercontent.com/assets/23391197/22047327/2f08f41a-dcdb-11e6-99eb-1cf3c85abc0e.png)

**Comment by melpete** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/23391197/22047329/33fe0f46-dcdb-11e6-9182-300fef2bee5e.png)
![data and donuts 5](https://cloud.githubusercontent.com/assets/23391197/22047331/35b89108-dcdb-11e6-942f-b7199af37781.png)

**Comment by melpete** [comment]
![los_angeles_county_california_seal](https://cloud.githubusercontent.com/assets/23391197/22047571/b2459256-dcdc-11e6-9175-fa865d321253.png)
![la_city_logo_med](https://cloud.githubusercontent.com/assets/23391197/22047594/e38956fe-dcdc-11e6-844f-955abbe97c19.png)

**Comment by melpete** [comment]
![seal of los angeles_city_controller_300px](https://cloud.githubusercontent.com/assets/23391197/22047605/ecf90964-dcdc-11e6-802e-4f4dbd464e4a.png)
![rg logo png](https://cloud.githubusercontent.com/assets/23391197/22047607/ef063006-dcdc-11e6-9f56-d2a6efaa7e43.PNG)

**Comment by matikin9** [comment]
https://data-donuts-matikin9.c9users.io/

**Comment by vykster** [comment]
Thank you so much Nina.

**Comment by matikin9** [comment]
![data and donuts transparent 2](https://cloud.githubusercontent.com/assets/1873072/22084410/e38eaf8e-dd84-11e6-8dbb-c5887a132006.png)
![lacountyheader_logo](https://cloud.githubusercontent.com/assets/1873072/22084411/e4d012de-dd84-11e6-8fb9-488eb7c8bc56.png)

**Comment by matikin9** [comment]
![data and donuts transparent](https://cloud.githubusercontent.com/assets/1873072/22085597/880d7a00-dd89-11e6-8a18-283a014822fa.png)

**Comment by vykster** [comment]
@matikin9 let me know when you want me to update DNS/ what you need set up re fwding.

**Comment by melpete** [comment]
@matikin9 @vykster 

**Some language Juan and I had used to describe data and donuts on our site:**

Join the change-makers and do-ers that are transforming government from the inside out for LA’s first Data & Donuts Speaker Series.

About Data & Donuts:
The Civic Tech community is small — but it’s nimble and passionate about getting things done. Data & Donuts brings together those working on civic tech — in government, in communities, in the arts, in non-profits and in private business — to share what they’re up to, inspire others to join our community and learn tips for success from change-makers across the City and County.

Event Rundown:
The two hour event begins promptly at 8 AM with coffee, donuts and networking. Next, our featured speaker (or panel) has 20 minutes to give their story on data and answer questions from the civic tech community. After Q&A, the remaining time is open for networking and last minute snacking.
