### ISSUE TITLE
Potential Speaker: Vandana Joshi

### ISSUE THREAD

**Issue by emillipede** [compilerla/data-donuts#53]
Department of Mental Health, Program Head, Data/GIS Unit

vjoshi@dmh.lacounty.gov

**Comment by vykster** [comment]
@emillipede are there any particular projects you think we should ask her to speak to?

**Comment by emillipede** [comment]
I'm curious about her experience with the county's GIS steering committee's [data sub-group](https://egis3.lacounty.gov/eGIS/egis-home/gis-data-committee/). I'd also like to know more about the DMH's involvement with collaborative projects like [The Source](https://www.lapl.org/stable-living/the-source).

**Comment by emillipede** [comment]
now at UCLA, would I think still be an awesome speaker
