### ISSUE TITLE
Potential Speaker: Helmi Hisserich

### ISSUE THREAD

**Issue by emillipede** [compilerla/data-donuts#59]
Helmi completed a Stanton fellowship. Her focus was housing. She’d like to develop a housing data library and regional archive. Would be a great presentation!

**Comment by hhisserich** [comment]
The project I worked on as a Stanton Fellow just got selected by the Bloomberg New Economy Solutions as one of the top 20 ideas worldwide for solving complex problems.  I'd be glad to do a presentation about this.  Thanks for mentioning.
