### ISSUE TITLE
Swag!

### ISSUE THREAD

**Issue by vykster** [compilerla/data-donuts#6]
This is supposed to be fun, inspiring and cool, so swag of course!

Stickers for attendees of logo?
Tote bags as a thank you for speakers?

**Comment by melpete** [comment]
I love both ideas. Need any help with ordering stuff?

**Comment by vykster** [comment]
@melpete yes please!

I can help with costs too. Also, can you share raw files and/or a .png of the logo (so I can use on web, etc).

I've ordered from stickermule before and like them, or do you know of someone local you'd prefer to use? I think it's best to go with vinyl stickers.

I have a local vendor for tote bags somewheres, let me look them up.

**Comment by melpete** [comment]
@vykster Don't know of anyone local. So stickermule is cool.

**Comment by melpete** [comment]
![data and donuts 5](https://cloud.githubusercontent.com/assets/23391197/20578745/bda57434-b17d-11e6-97f6-319944e5df72.png)

**Comment by melpete** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/23391197/20578758/cb85c478-b17d-11e6-9885-bd87287499bb.png)

**Comment by melpete** [comment]
@vykster Did I upload those correctly? haha I'm a total newb to GitHub

**Comment by vykster** [comment]
@melpete Thank you!

Mind sending me the raw file via email?

I need a transparent .png of just the donut shape for the website and email.

**Comment by vykster** [comment]
@melpete looks like tote bag for our speaker will be ready in time too! Picking the batch up on Wednesday!
