### ISSUE TITLE
RSVP button does not appear to work

### ISSUE THREAD

**Issue by thzinc** [compilerla/data-donuts#67]
On event pages, the RSVP button links to a nonexistant `#rsvp` anchor. 

Example: https://datadonuts.la/event/data-donuts-18.html

I was looking for the Eventbrite link, which I ended up finding in the Markdown file for the post. Seems like the site template might need a change to make this work.

**Comment by thekaveman** [comment]
Maybe you saw a version of the page before the Eventbrite embed got in there? When I click on the RSVP button I see the Eventbrite sign-up form:

![image](https://user-images.githubusercontent.com/1783439/48093528-77875e80-e1c4-11e8-82bb-72f9d45a8f08.png)

**Comment by thzinc** [comment]
Ah, sure enough. The Eventbrite embed definitely was not there when I posted this issue, but it's there now.

Thanks for looking at this. :)
