### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by matikin9** [compilerla/data-donuts#7]
Initial requirements:
- 40-50 people

Concerns:
- Neutral space
- Parking/public transit

Options:
- Outdoor spaces
- California Endowment
- Union Station
- LACI (La Kretz Innovation Center)

**Comment by Jon-Neill** [comment]
California Endowment - Los Angeles Campus

http://www.calendow.org/centers/los-angeles-conference-center/

Contact: 
Sue Ko - 213-928-8610 (Main contact, very busy)
Meg: 213-928-8613 (Try her first)

Need a minimum of 3 weeks lead time.

**Comment by melpete** [comment]
LACI amphitheatre reserved for Feb 2. Confirmed by Clare Le and Michael Swords.
