### ISSUE TITLE
Marketing Materials

### ISSUE THREAD

**Issue by matikin9** [compilerla/data-donuts#9]
- One page pitch deck flyer for GIS Day

**Comment by melpete** [comment]
[data n donuts white bg.pdf](https://github.com/compilerla/data-donuts/files/593444/data.n.donuts.white.bg.pdf)

**Comment by melpete** [comment]
[data n donuts.pdf](https://github.com/compilerla/data-donuts/files/593446/data.n.donuts.pdf)

**Comment by vykster** [comment]
![data n donuts white bg](https://cloud.githubusercontent.com/assets/4284662/20337872/882d5ec0-ab88-11e6-8d39-6aabf33ef70a.png)

**Comment by vykster** [comment]
@melpete tip, if you upload a .png file it will display :)

**Comment by matikin9** [comment]
there we go, I like it with the shortened text.

**Comment by melpete** [comment]
@vykster Oops Yup! Thank you

**Comment by matikin9** [comment]
One pager Google Doc: https://docs.google.com/document/d/1dMUVQz8lPoijIkBp8XeUtUqLo56X0gLdnvw6VEx9bpk/edit

**Comment by matikin9** [comment]
Flyer updated for Feb 2 date:
[DataDonutsFlyer 01-17-17.pdf](https://github.com/compilerla/data-donuts/files/714817/DataDonutsFlyer.01-17-17.pdf)
