### ISSUE TITLE
Update failed to deploy -- Error message in GitHub Actions

### ISSUE THREAD

**Issue by vykster** [compilerla/data-donuts#97]
<img width="1361" alt="Screenshot 2023-05-17 at 4 40 47 PM" src="https://github.com/compilerla/data-donuts/assets/4284662/dd4ea82b-9d2b-4c6f-a2e6-689f52597dae">

**Comment by vykster** [comment]
updated md files as usual, have not updated site since Sept 2021, after merging PR, failed to deploy to gh-pages. github actions shows and error, two years ago gh actions did not exist.

**Comment by thekaveman** [comment]
GitHub did change the way Pages sites are built and deployed in December 2021, to build on the Actions system: https://github.blog/changelog/2021-12-16-github-pages-using-github-actions-for-builds-and-deployments-for-public-repositories/

I think the deploy went out though? Is this correct: https://datadonuts.la/event/data-donuts-36.html ?

**Comment by vykster** [comment]
yes. thx @thekaveman @machikoyasuda
